### ISSUE TITLE
NbisEventsScraper failure

### ISSUE THREAD

**Issue by fbacall** [ElixirTeSS/TeSS_scrapers#55]
```
NbisEventsScraper: undefined method `match' for nil:NilClass
        /home/tess/TeSS_scrapers/app/scrapers/nbis_events_scraper.rb:44:in `parse_description'
        /home/tess/TeSS_scrapers/app/scrapers/nbis_events_scraper.rb:25:in `block in scrape'
        /home/tess/TeSS_scrapers/app/scrapers/nbis_events_scraper.rb:23:in `each'
        /home/tess/TeSS_scrapers/app/scrapers/nbis_events_scraper.rb:23:in `scrape'
        /home/tess/TeSS_scrapers/lib/tess/scrapers/scraper.rb:35:in `run'
        run_scrapers.rb:58:in `block in <main>'
        run_scrapers.rb:55:in `each'
        run_scrapers.rb:55:in `<main>'
```

**Comment by knirirr** [comment]
Looks like the URL matching is no longer working.
I've temporarily checked in a change that will stop the error emails, and will attempt a further fix now.
